### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\workshop\\DC\\DDKG-main/data\\drugbank_id_smile.npy'

### ISSUE THREAD

**Issue by Dingyijiang1** [Blair1213/DDKG#1]
Hi.
The error is shown as following:
Traceback (most recent call last):
  File "E:/workshop/DC/DDKG-main/run.py", line 239, in <module>
    process_data('kegg',NEIGHBOR_SIZE['kegg'],4)
  File "E:/workshop/DC/DDKG-main/run.py", line 160, in process_data
    cross_validation(K, examples, dataset, neighbor_sample_size)
  File "E:/workshop/DC/DDKG-main/run.py", line 192, in cross_validation
    train_log = train(
  File "E:\workshop\DC\DDKG-main\main.py", line 78, in train
    config.drug_smile = np.load(format_filename(PROCESSED_DATA_DIR, DRUG_SMILE_TEMPLATE),allow_pickle=True)
  File "E:\anacoda\lib\site-packages\numpy\lib\npyio.py", line 407, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\workshop\\DC\\DDKG-main/data\\drugbank_id_smile.npy'

How can I mend this error?

**Comment by Blair1213** [comment]
Hi! I have updated the file and you could find it in 'data' folder now.
